version: '3'

services:
    workspace:
        build:
            context: ..
            dockerfile: Dockerfile
        environment:
            PYTHONPATH: /workspace
        volumes:
            - ..:/workspace
        command: sleep infinity