version: '3'

services:
    workspace:
        build:
            context: ..
            dockerfile: Dockerfile
        environment:
            PYTHONPATH: /workspace
        ports:
            - 8000:8000
        volumes:
            - ..:/workspace
        command: sleep infinity

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data: